# Generated by Django 3.0.12 on 2021-02-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Qna',
        ),
    ]
